In [20]:
import numpy as np
import pandas as pd

In [21]:
board=np.zeros((8,8))
board

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [22]:
# player=0 => vertical ; player=1 => horizontal

def possible_moves(board,player):
    l=[]
    if player==1:
        for i in range(board.shape[0]):
            for j in range(board.shape[1]):
                if board[i][j]==0:
                    try:
                        if board[i][j+1]==0:
                            l.append(i*8+j)
                    except:
                        z=0
    elif player==0:
        for i in range(board.shape[0]):
            for j in range(board.shape[1]):
                if board[i][j]==0:
                    try:
                        if board[i+1][j]==0:
                            l.append(i*8+j)
                    except:
                        z=0

        
                        
                        
                        
    return l

       

In [23]:
import random

def playout(board,player_init):
    brd=np.copy(board)
    bool=False
    player=player_init
    p_m=possible_moves(brd,player)
    if len(p_m)>0:
        bool=True
    while bool:

        a=random.randint(0,len(p_m)-1)
        
        r_m=p_m[a]
        
        brd=play(brd,r_m,player)
        player=1-player
        p_m=possible_moves(brd,player)
        if len(p_m)==0:
            bool=False
    return 1-player
        


In [24]:
def mean_playout(board,player,ite=100):

    l= np.vstack([
        [
            playout(board,player)


        ]
        for i in range(ite)])

    return l.mean()


In [25]:
def play(board,move,player):
    i=move//8
    j=move%8
    board[i,j]+=1
    if player==0:
        board[i+1,j]+=1
    elif player==1:
        board[i,j+1]+=1
        
    return board
    

In [26]:
def domineering_game(size,starting_player=0):
    list_best_moves=[]
    board=np.zeros((size,size))
    player=starting_player
    bool=False
    p_m=possible_moves(board,player)
    if len(p_m)>0:
        bool=True
        
        
    while bool==True:
        print(len(p_m))
        
        l1=[]
        l2=[]

        for i in range(len(p_m)):
            brd=np.copy(board)
            brd=play(brd,p_m[i],player)
            l1.append(mean_playout(brd,1-player,10))
            l2.append(p_m[i])
        
        
        #MAKE SURE player=0 or player=1
        if player==1:
            best_playout=2
            for j in range(len(l1)):
                if l1[j]<best_playout:
                    best_playout=l1[j]
                    best_move=l2[j]
                    
            
            
        elif player==0:
            best_playout=-1
            for j in range(len(l1)):
                if l1[j]>best_playout:
                    best_playout=l1[j]
                    best_move=l2[j]
                    
        list_best_moves.append(best_move)
        print(best_move)
        print(player)
        print('')
                    
        board=play(board,best_move,player)
        player=1-player
        p_m=possible_moves(board,player)
        if len(p_m)==0:
            bool=False
            
    return 1-player,list_best_moves
            
        

        

In [27]:
z,q=domineering_game(8)

56
0
0

54
32
1

50
16
0

50
28
1

45
45
0

43
2
1

40
15
0

38
60
1

36
44
0

33
6
1

33
40
0

29
11
1

28
9
0

24
4
1

24
18
0

20
46
1

17
35
0

16
19
1

13
22
0

12
56
1

9
31
0

9
50
1

5
13
0

6
37
1

4
34
0

3
58
1

3
41
0

2
54
1



In [28]:
board=np.zeros((8,8))
player=0
for a in q:
    print(a)
    board=play(board,a,player)
    print(board)
    print("")
    player=1-player

0
[[ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]

32
[[ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]

16
[[ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]

28
[[ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  1.  1.  0.  0.]
 [ 

In [29]:
liste_moves=[]

for i in range(20):
    print("Nous jouons la " + str(i) + "ème partie.")
    z,q=domineering_game(8)
    liste_moves.append(q)
    print("")
    
    

56
23
0

54
3
1

51
8
0

49
19
1

44
14
0

43
33
1

37
2
0

37
50
1

31
41
0

31
43
1

26
13
0

27
11
1

23
32
0

26
0
1

19
47
0

23
56
1

15
18
0

18
58
1

14
9
0

16
5
1

12
52
0

12
24
1

11
37
0

8
28
1

7
7
0

5
61
1

4
38
0

2
53
1

1
27
0

56
23
0

54
61
1

51
50
0

47
26
1

45
10
0

40
2
1

42
5
0

33
21
1

37
1
0

29
40
1

31
4
0

26
16
1

26
28
0

22
19
1

22
48
0

19
59
1

19
0
0

18
32
1

16
45
0

12
24
1

14
44
0

9
34
1

11
49
0

8
29
1

8
38
0

4
54
1

4
43
0

2
6
1

1
39
0

1
14
1

56
22
0

52
14
1

50
29
0

47
6
1

47
13
0

43
1
1

43
10
0

36
25
1

38
44
0

29
4
1

34
3
0

26
46
1

28
27
0

21
49
1

21
0
0

17
57
1

19
24
0

13
60
1

15
23
0

10
40
1

11
20
0

7
33
1

7
48
0

6
38
1

6
9
0

4
42
1

4
45
0

2
54
1

1
51
0

1
62
1

56
42
0

52
40
1

49
2
0

47
58
1

46
27
0

40
0
1

41
17
0

35
52
1

34
16
0

32
33
1

30
5
0

26
60
1

28
31
0

22
6
1

23
43
0

20
14
1

20
12
0

16
3
1

16
21
0

12
45
1

11
30
0

8
8
1

9
36
0

6
22
1

7
47
0

4
56
1

3
11
0

2
48
1

2


In [30]:
liste_arr=[]
for a in liste_moves:
    player=0
    board=np.zeros((8,8))
    
    for move in a:
        a1=board.reshape(64)
        a2=(1-board).reshape(64)
        a3=(np.zeros((8,8))+player).reshape(64)
        a4=np.zeros((8,8)).reshape(64)
        a4[move]=1
        liste_arr.append(np.concatenate((a1,a2,a3,a4),axis=0))
        board=play(board,move,player)
        player=1-player
        
dataset= np.vstack([
        [
            lol


        ]
        for lol in liste_arr])
        
    

In [31]:
dataset.shape

(582, 256)

In [32]:
X_test=[]
Y_test=[]

for a in dataset:
    X_test.append(a[:192].reshape(3,8,8))
    Y_test.append(a[192:256].reshape(1,8,8))

In [33]:
x_test=np.asarray(X_test)
y_test=np.asarray(Y_test)

In [121]:
#Extraction et data augmentation.

def symetrie(array,opt):
    arr=np.zeros((8,8))
    
    if opt==1:
        for i in range(8):
            for j in range(8):
                arr[i,j]=array[i,7-j]
    elif opt==2:
        for i in range(8):
            for j in range(8):
                arr[i,j]=array[7-i,j]
    elif opt==3:
        for i in range(8):
            for j in range(8):
                arr[i,j]=array[7-i,7-j]
                
    return(arr)
    
    
    
    
    

dataflow=pd.read_csv('C:/Data_analysis/domineering.csv')
a=dataflow.values
t=np.copy(a)

l=[]
for i in range(4):
    rotato= np.vstack([
[
        #np.rot90(a.reshape(4,8,8)[i])
        symetrie(a.reshape(4,8,8)[i],opt=1)


]
        for a in t])
    l.append(rotato)
    
rot1=np.concatenate((l[0],l[1],l[2],l[3]),axis=0).reshape(t.shape[0],256)


t2=np.copy(rot1)

l=[]
for i in range(4):
    rotato= np.vstack([
[
        #np.rot90(a.reshape(4,8,8)[i])
        symetrie(a.reshape(4,8,8)[i],opt=2)


]
        for a in t2])
    l.append(rotato)
    
rot2=np.concatenate((l[0],l[1],l[2],l[3]),axis=0).reshape(t2.shape[0],256)


t3=np.copy(rot2)

l=[]
for i in range(4):
    rotato= np.vstack([
[
        #np.rot90(a.reshape(4,8,8)[i])
        symetrie(a.reshape(4,8,8)[i],opt=3)


]
        for a in t2])
    l.append(rotato)
    
rot3=np.concatenate((l[0],l[1],l[2],l[3]),axis=0).reshape(t3.shape[0],256)




data_augmented=np.concatenate((a,rot1,rot2,rot3),axis=0)
np.random.shuffle(data_augmented)




X_train=[]
Y_train=[]

for a in data_augmented:
    X_train.append(a[:192].reshape(3,8,8))
    Y_train.append(a[192:256].reshape(1,8,8))
    
x_train=np.asarray(X_train)
y_train=np.asarray(Y_train)
    

In [122]:
x_train.shape,y_train.shape,x_test.shape,y_test.shape

((112616, 3, 8, 8), (112616, 1, 8, 8), (582, 3, 8, 8), (582, 1, 8, 8))

In [123]:
from __future__ import print_function
import keras
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D
from keras import backend as K
import numpy as np
from keras.layers import Dense, Dropout, Activation, Flatten, Reshape
from keras.optimizers import SGD

K.set_image_data_format('channels_first')
K.image_data_format()

'channels_first'

In [124]:
model = Sequential()#192=8*8*3, 192 matrice 8*8 en sortie correspond au filtre et 3*3 comment ils sont séparés
model.add(Conv2D(128,kernel_size=(3, 3), padding='same', activation='relu',input_shape=(3,8,8)))# pas de vanish gradient 
                                                                                                #avec relu
model.add(Dropout(0.25))
model.add(Conv2D(64,kernel_size=(3, 3), padding='same', activation='relu'))

model.add(Conv2D(32,kernel_size=(3, 3), padding='same',activation='relu'))
model.add(Dropout(0.25))
#model.add(Conv2D(64,kernel_size=(3, 3), padding='same',activation='relu'))
#model.add(Dropout(0.25))
#model.add(Conv2D(64,kernel_size=(3, 3), padding='same',activation='relu'))
#model.add(Dropout(0.25))
model.add(Conv2D(1,kernel_size=(3, 3), padding='same',activation='relu'))
model.add(Dropout(0.25))
model.add(Reshape((1,1,64)))
model.add(Activation('softmax'))#une dimension
model.add(Reshape((1,8,8)))
model.compile(loss='mse',#minumum square error keras.losses.categorical_crossentropy, 
              optimizer='adam', #technique de gradient descent stochastique (min globale)
              metrics=['accuracy'])




batch_size = 128 #take 128 samples and train network
nb_epoch = 2 #propagation-backpropagation
model.fit(x_train, y_train, batch_size=batch_size, epochs=nb_epoch, verbose=1, shuffle=True,validation_data=(x_test, y_test))
score = model.evaluate(x_test, y_test, verbose=0)#mélanger les exemples de train
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Train on 112616 samples, validate on 582 samples
Epoch 1/2
112616/112616 [==============================] - 405s 4ms/step - loss: 0.2780 - acc: 0.2206 - val_loss: 0.0152 - val_acc: 0.2098
Epoch 2/2
112616/112616 [==============================] - 386s 3ms/step - loss: 0.2775 - acc: 0.2448 - val_loss: 0.0152 - val_acc: 0.2582
Test loss: 0.0152293574257
Test accuracy: 0.258161511823


In [128]:
#LE JOUEUR 0 va utiliser le CNN pendant que le joueur 1 joue random.
moves=[]
winner=[]
nb_ite=1000
for i in range(nb_ite):
    if i%100==0:
        print(str(i) + " itérations complétées")
    board=np.zeros((8,8))
    player=0
    list_mo=[]
    while len(possible_moves(board,player))>0:
        if player==0:

            X=np.concatenate((board,1-board,np.zeros((8,8))+player),axis=0).reshape(1,3,8,8)
            Y=model.predict(X).reshape(64)
            boolo=False

            max=-1
            cpt=0
            while boolo==False and cpt<64:
                cpt=cpt+1
                for i in range(64):
                    if Y[i]>max:
                        max=Y[i]
                        move=i
                if move in possible_moves(board,player):
                    list_mo.append(move)
                    board=play(board,move,player)
                    player=1-player
                    boolo=True
                else:
                    Y[move]=0
                    max=-1

        elif player==1:
            p_m=possible_moves(board,player)
            a=random.randint(0,len(p_m)-1)

            r_m=p_m[a]
            list_mo.append(r_m)
            board=play(board,r_m,player)
            player=1-player
            
    moves.append(list_mo)
    winner.append(1-player)
    





    
board
    

0 itérations complétées
100 itérations complétées
200 itérations complétées
300 itérations complétées
400 itérations complétées
500 itérations complétées
600 itérations complétées
700 itérations complétées
800 itérations complétées
900 itérations complétées


array([[ 0.,  1.,  0.,  1.,  0.,  1.,  1.,  1.],
       [ 0.,  1.,  0.,  1.,  1.,  1.,  1.,  1.],
       [ 0.,  1.,  1.,  0.,  1.,  1.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  1.,  1.,  1.,  0.],
       [ 0.,  1.,  1.,  1.,  1.,  0.,  1.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  1.,  0.,  1.,  0.]])

In [129]:
cpt1=0
cpt2=0
for a in winner:
    if a==0:
        cpt1+=1
    elif a==1:
        cpt2+=1
print('Sur ' + str(nb_ite) + ' parties, le joueur 0 a gagné ' + str(cpt1) + ' fois tandis que le joueur 1 a gagné ' + str(cpt2) + ' fois.')
        

Sur 1000 parties, le joueur 0 a gagné 989 fois tandis que le joueur 1 a gagné 11 fois.


In [134]:
#LE JOUEUR 0 va utiliser le CNN pendant que le joueur 1 joue avec monte carlo.
moves=[]
winner=[]
nb_ite=50
for i in range(nb_ite):
    if i%10==0:
        print(str(i) + " itérations complétées")
    board=np.zeros((8,8))
    player=0
    list_mo=[]
    while len(possible_moves(board,player))>0:
        if player==0:

            X=np.concatenate((board,1-board,np.zeros((8,8))+player),axis=0).reshape(1,3,8,8)
            Y=model.predict(X).reshape(64)
            boolo=False

            max=-1
            cpt=0
            while boolo==False and cpt<64:
                cpt=cpt+1
                for i in range(64):
                    if Y[i]>max:
                        max=Y[i]
                        move=i
                if move in possible_moves(board,player):
                    list_mo.append(move)
                    board=play(board,move,player)
                    player=1-player
                    boolo=True
                else:
                    Y[move]=0
                    max=-1

        elif player==1:
            p_m=possible_moves(board,player)
                        
            l1=[]
            l2=[]

            for i in range(len(p_m)):
                brd=np.copy(board)
                brd=play(brd,p_m[i],player)
                l1.append(mean_playout(brd,1-player,10))
                l2.append(p_m[i])


           
        
            best_playout=-1
            for j in range(len(l1)):
                if l1[j]>best_playout:
                    best_playout=l1[j]
                    best_move=l2[j]
                    
                    
            list_mo.append(best_move)
            board=play(board,best_move,player)
            player=1-player

 
            
            
            
            
            
            
            
            
    moves.append(list_mo)
    winner.append(1-player)

0 itérations complétées
10 itérations complétées
20 itérations complétées
30 itérations complétées
40 itérations complétées


In [135]:
cpt1=0
cpt2=0
for a in winner:
    if a==0:
        cpt1+=1
    elif a==1:
        cpt2+=1
print('Sur ' + str(nb_ite) + ' parties, le joueur 0 a gagné ' + str(cpt1) + ' fois tandis que le joueur 1 a gagné ' + str(cpt2) + ' fois.')


Sur 50 parties, le joueur 0 a gagné 39 fois tandis que le joueur 1 a gagné 11 fois.
