In [13]:
import numpy as np
import pandas as pd

In [14]:
board=np.zeros((8,8))
board

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
# player=0 => vertical ; player=1 => horizontal

def possible_moves(board,player):
    l=[]
    if player==1:
        for i in range(board.shape[0]):
            for j in range(board.shape[1]):
                if board[i][j]==0:
                    try:
                        if board[i][j+1]==0:
                            l.append(i*8+j)
                    except:
                        z=0
    elif player==0:
        for i in range(board.shape[0]):
            for j in range(board.shape[1]):
                if board[i][j]==0:
                    try:
                        if board[i+1][j]==0:
                            l.append(i*8+j)
                    except:
                        z=0

        
                        
                        
                        
    return l

       

In [16]:
import random

def playout(board,player_init):
    brd=np.copy(board)
    bool=False
    player=player_init
    p_m=possible_moves(brd,player)
    if len(p_m)>0:
        bool=True
    while bool:

        a=random.randint(0,len(p_m)-1)
        
        r_m=p_m[a]
        
        brd=play(brd,r_m,player)
        player=1-player
        p_m=possible_moves(brd,player)
        if len(p_m)==0:
            bool=False
    return 1-player
        


In [17]:
def mean_playout(board,player,ite=100):

    l= np.vstack([
        [
            playout(board,player)


        ]
        for i in range(ite)])

    return l.mean()


In [18]:
def play(board,move,player):
    i=move//8
    j=move%8
    board[i,j]+=1
    if player==0:
        board[i+1,j]+=1
    elif player==1:
        board[i,j+1]+=1
        
    return board
    

In [19]:
def domineering_game(size,starting_player=0):
    list_best_moves=[]
    board=np.zeros((size,size))
    player=starting_player
    bool=False
    p_m=possible_moves(board,player)
    if len(p_m)>0:
        bool=True
        
        
    while bool==True:
        print(len(p_m))
        
        l1=[]
        l2=[]

        for i in range(len(p_m)):
            brd=np.copy(board)
            brd=play(brd,p_m[i],player)
            l1.append(mean_playout(brd,1-player,100))
            l2.append(p_m[i])
            
        if player==0:
            best_playout=2
            for j in range(len(l1)):
                if l1[j]<best_playout:
                    best_playout=l1[j]
                    best_move=l2[j]
                    
            
            
        elif player==1:
            best_playout=-1
            for j in range(len(l1)):
                if l1[j]>best_playout:
                    best_playout=l1[j]
                    best_move=l2[j]
                    
        list_best_moves.append(best_move)
        print(best_move)
        print(player)
        print('')
                    
        board=play(board,best_move,player)
        player=1-player
        p_m=possible_moves(board,player)
        if len(p_m)==0:
            bool=False
            
    return 1-player,list_best_moves
            
        

        

In [20]:
z,q=domineering_game(8)

56
1
0

52
4
1

52
19
0

45
30
1

45
35
0

39
14
1

39
33
0

33
54
1

32
17
0

27
20
1

27
52
0

21
36
1

21
38
0

16
10
1

17
49
0

10
50
1

13
45
0

8
2
1

11
32
0

7
22
1

8
0
0

6
61
1

6
18
0

4
6
1

4
16
0

3
12
1

3
34
0

2
28
1

2
39
0

1
58
1

1
48
0



In [22]:
board=np.zeros((8,8))
player=0
for a in q:
    print(a)
    board=play(board,a,player)
    print(board)
    print("")
    player=1-player

1
[[0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]

4
[[0. 1. 0. 0. 1. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]

19
[[0. 1. 0. 0. 1. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]

30
[[0. 1. 0. 0. 1. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]

35
[[0. 1. 0. 0. 1. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 1. 1.]
 [0. 0.

In [25]:
liste_moves=[]

for i in range(20):
    z,q=domineering_game(8)
    liste_moves.append(q)
    
    

56
5
0

52
14
1

50
48
0

49
36
1

44
50
0

42
30
1

38
54
0

36
11
1

32
1
0

30
20
1

28
52
0

23
26
1

22
38
0

17
24
1

17
33
0

12
42
1

12
10
0

8
44
1

9
8
0

6
2
1

7
32
0

4
6
1

6
39
0

3
22
1

4
49
0

2
28
1

3
51
0

1
34
1

2
53
0

56
49
0

52
14
1

50
19
0

46
28
1

43
17
0

40
30
1

36
0
0

37
11
1

31
32
0

32
1
1

26
54
0

26
44
1

20
34
0

19
52
1

15
51
0

14
46
1

10
13
0

11
35
1

7
10
0

8
3
1

5
16
0

6
5
1

4
33
0

4
22
1

3
48
0

3
37
1

2
50
0

1
60
1

1
55
0

56
1
0

52
10
1

50
49
0

46
46
1

44
25
0

40
36
1

37
31
0

35
62
1

33
51
0

29
52
1

27
5
0

23
14
1

21
21
0

18
27
1

17
34
0

13
40
1

12
18
0

10
43
1

10
12
0

7
16
1

6
22
0

5
2
1

4
0
0

3
6
1

3
24
0

2
54
1

2
48
0

1
60
1

1
50
0

56
26
0

52
46
1

49
54
0

46
32
1

44
9
0

41
30
1

37
36
0

35
14
1

30
52
0

29
10
1

25
19
0

24
48
1

19
4
0

19
50
1

13
0
0

17
20
1

8
5
0

14
1
1

7
16
0

11
6
1

6
29
0

8
22
1

4
35
0

6
38
1

3
45
0

5
40
1

1
55
0

3
56
1

56
1
0

52
10
1

50
46
0

46

In [26]:
liste_arr=[]
for a in liste_moves:
    player=0
    board=np.zeros((8,8))
    
    for move in a:
        a1=board.reshape(64)
        a2=(1-board).reshape(64)
        a3=(np.zeros((8,8))+player).reshape(64)
        a4=np.zeros((8,8)).reshape(64)
        a4[move]=1
        liste_arr.append(np.concatenate((a1,a2,a3,a4),axis=0))
        board=play(board,move,player)
        player=1-player
        
dataset= np.vstack([
        [
            lol


        ]
        for lol in liste_arr])
        
    

In [35]:
dataset.shape

(577, 256)

In [37]:
X_test=[]
Y_test=[]

for a in dataset:
    X_test.append(a[:192].reshape(3,8,8))
    Y_test.append(a[192:256].reshape(1,8,8))

In [38]:
x_test=np.asarray(X_test)
y_test=np.asarray(Y_test)

In [39]:
dataflow=pd.read_csv('C:/Data_analysis/domineering.csv')
a=dataflow.values
t=np.copy(a)

l=[]
for i in range(4):
    rotato= np.vstack([
[
        np.rot90(a.reshape(4,8,8)[i])


]
        for a in t])
    l.append(rotato)
    
rot1=np.concatenate((l[0],l[1],l[2],l[3]),axis=0).reshape(t.shape[0],256)


t2=np.copy(rot1)

l=[]
for i in range(4):
    rotato= np.vstack([
[
        np.rot90(a.reshape(4,8,8)[i])


]
        for a in t2])
    l.append(rotato)
    
rot2=np.concatenate((l[0],l[1],l[2],l[3]),axis=0).reshape(t2.shape[0],256)


t3=np.copy(rot2)

l=[]
for i in range(4):
    rotato= np.vstack([
[
        np.rot90(a.reshape(4,8,8)[i])


]
        for a in t2])
    l.append(rotato)
    
rot3=np.concatenate((l[0],l[1],l[2],l[3]),axis=0).reshape(t3.shape[0],256)


data_augmented=np.concatenate((a,rot1,rot2,rot3),axis=0)
np.random.shuffle(data_augmented)




X_train=[]
Y_train=[]

for a in data_augmented:
    X_train.append(a[:192].reshape(3,8,8))
    Y_train.append(a[192:256].reshape(1,8,8))
    
x_train=np.asarray(X_train)
y_train=np.asarray(Y_train)
    

In [40]:
x_train.shape,y_train.shape,x_test.shape,y_test.shape

((112616, 3, 8, 8), (112616, 1, 8, 8), (577, 3, 8, 8), (577, 1, 8, 8))

In [41]:
from __future__ import print_function
import keras
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D
from keras import backend as K
import numpy as np
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.datasets import mnist
from keras.optimizers import SGD

K.set_image_data_format('channels_first')
K.image_data_format()

C:\Users\jean-\Anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


'channels_first'

In [42]:
model = Sequential()
model.add(Conv2D(32,kernel_size=(3, 3), padding='same', activation='relu',input_shape=(3,8,8)))# pas de vanish gradient avec relu
model.add(Dropout(0.25))
model.add(Conv2D(64,kernel_size=(3, 3), padding='same', activation='relu'))
model.add(Dropout(0.25))
model.add(Conv2D(32,kernel_size=(3, 3), padding='same',activation='relu'))
model.add(Dropout(0.25))
model.add(Conv2D(1, (3,3),padding="same", activation='relu'))
model.add(Dropout(0.25))
model.compile(loss='mse',#minumum square error keras.losses.categorical_crossentropy, 
              optimizer='adam', #technique de gradient descent stochastique (min globale)
              metrics=['accuracy'])
batch_size = 128
nb_epoch = 5    #propagation-backpropagation
model.fit(x_train, y_train, batch_size=batch_size, epochs=nb_epoch, verbose=1, validation_data=(x_test, y_test))
score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Train on 112616 samples, validate on 577 samples
Epoch 1/5
112616/112616 [==============================] - 124s 1ms/step - loss: 0.1381 - acc: 0.2862 - val_loss: 0.0339 - val_acc: 0.7506
Epoch 2/5
112616/112616 [==============================] - 130s 1ms/step - loss: 0.1270 - acc: 0.3958 - val_loss: 0.0358 - val_acc: 0.7944
Epoch 3/5
112616/112616 [==============================] - 131s 1ms/step - loss: 0.1240 - acc: 0.4342 - val_loss: 0.0340 - val_acc: 0.8016
Epoch 4/5
112616/112616 [==============================] - 128s 1ms/step - loss: 0.1227 - acc: 0.4419 - val_loss: 0.0340 - val_acc: 0.8200
Epoch 5/5
112616/112616 [==============================] - 123s 1ms/step - loss: 0.1216 - acc: 0.4496 - val_loss: 0.0379 - val_acc: 0.8143
Test loss: 0.03793431196419887
Test accuracy: 0.8143414211438474
